---
- name: Configure firewall for PostgreSQL as a container
  include_tasks: tasks/firewall-setup.yml
  vars:
    ports:
      - 5432/tcp
    firewall_zone: trusted
  tags:
    - database

- name: Prerequisite PostgreSQL
  include_tasks: tasks/{{ container_runtime }}/prerequisite.yml
  tags:
    - database

- name: Deploy PostgreSQL
  include_tasks: tasks/{{ container_runtime }}/deploy.yml
  tags:
    - database

- name: Test PostgreSQL
  include_tasks: tasks/healthcheck.yml
