---
- name: Install Docker and dependencies
  become: yes
  yum:
    name: "{{ docker_packages }}" 
    state: latest
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database
    - docker

- name: Start and enable docker
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database
    - docker

- name: Deploy docker to redis container host
  become: yes
  include_tasks: tasks/deploy-docker.yml
  vars:
    docker_packages:
      - docker
      - python-docker-py
  when: quay_redis_containerize
  tags:
    - redis
