---
- name: Create {{ quay_root_dir }}/redis
  file:
    path: "{{ quay_root_dir }}/redis"
    state: directory
    mode: '0777'
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database

- name: Deploy Redis container
  podman_container:
    detach: yes
    restart: yes
    name: "redis"
    privileged: yes
    published_ports: 6379:6379
    volumes: "{{ quay_root_dir }}/redis:/var/lib/redis/data:Z"
    image: "registry.redhat.io/rhscl/redis-5-rhel7"
    env:
      REDIS_PASSWORD: "{{ quay_redis_password }}"
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database
