---
- name: Install netcat if it isn't there already
  yum:
    name: nmap-ncat
    state: latest
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database

- name: Test if Redis is up and talking
  shell: printf "PING\r\n" | nc localhost 6379
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database
