---
# tasks file for ansible-role-containers-redis
- name: Configure firewall for Redis
  include_tasks: tasks/firewall-setup.yml
  vars:
    ports:
      - 6379/tcp
    firewall_zone: public
    when: quay_redis_deploy and not quay_redis_containerize
  tags:
    - redis

- name: Configure firewall for Redis container
  include_tasks: tasks/firewall-setup.yml
  vars:
    ports:
      - 6379/tcp
    firewall_zone: trusted
    when: quay_redis_deploy and quay_redis_containerize
  tags:
    - redis

- name: Prerequisite redis
  include_tasks: tasks/{{container_runtime}}/prerequisite.yml
  tags:
    - redis

- name: Login to registry
  include_tasks: tasks/{{container_runtime}}/login.yml
  tags:
    - redis

- name: Deploy redis container
  include_tasks: tasks/{{ container_runtime }}/deploy.yml
  when: quay_redis_containerize
  tags:
    - redis
