---
- name: Create env file on target
  become: yes
  template:
    src: templates/mysql-env-file
    dest: ~/mysql-env-file
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database

- name: Create /var/lib/mysql
  become: yes
  file:
    path: /var/lib/mysql
    state: directory
    mode: '0777'
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database

- name: Deploy mysql container
  become: yes
  podman_container:
    env_file: "~/mysql-env-file"
    detach: yes
    restart: yes
    name: "{{ mysql_container_name }}"
    privileged: yes
    published_ports: 3306:3306
    volumes: /var/lib/mysql:/var/lib/mysql/data:Z
    image: "{{ mysql_image }}"
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database
