---
# tasks file for ansible-role-containers-mysql
- name: Configure firewall for MySQL
  include_tasks: tasks/firewall-setup.yml
  vars:
    ports:
      - 3306/tcp
    firewall_zone: public
    when: not quay_database_containerize
  tags:
    - database

- name: Configure firewall for MySQL as a container
  include_tasks: tasks/firewall-setup.yml
  vars:
    ports:
      - 3306/tcp
    firewall_zone: trusted
    when: quay_database_containerize
  tags:
    - database

- name: Install prerequisites for mysql
  include_tasks: tasks/{{ container_runtime }}/prerequisite.yml
  tags:
    - database

- name: Login to registry
  include_tasks: tasks/{{container_runtime}}/login.yml

- name: Deploy MySQL
  include_tasks: tasks/{{ container_runtime }}/deploy.yml
  # when: quay_database_containerize
  tags:
    - database

- name: Test mysql
  include_tasks: tasks/healthcheck.yml
  tags:
    - database
