---
# tasks file for ansible-role-containers-mysql
- name: Configure firewall for MySQL
  include_tasks: tasks/firewall-setup.yml
  vars:
    ports:
      - 3306/tcp
    firewall_zone: public
    when: not QUAY_DATABASE_CONTAINERIZE
  tags:
    - database

- name: Configure firewall for MySQL as a container
  include_tasks: tasks/firewall-setup.yml
  vars:
    ports:
      - 3306/tcp
    firewall_zone: trusted
    when: QUAY_DATABASE_CONTAINERIZE
  tags:
    - database

- name: Deploy conatinerized mysql
  include_tasks: tasks/deploy-{{ container_runtime }}-container.yml
  when: QUAY_DATABASE_CONTAINERIZE
  tags:
    - database

- name: Deploy mysql
  include_role:
    name: robertdebock.mysql
  vars:
    _mysql_service: "{{ _quay_mysql_service }}"
    _mysql_packages: "{{ _quay_mysql_packages }}"
  when: not QUAY_DATABASE_CONTAINERIZE
  tags:
    - database

- name: Test mysql
  include_tasks: tasks/healthcheck.yml
  tags:
    - database
