---
- name: Ensure firewalld is installed
  become: yes
  yum:
    name: firewalld
    state: latest
  notify:
    - restart docker
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database

- name: Ensure firewalld is started
  become: yes
  systemd:
    name: firewalld
    state: started
    enabled: yes
  notify:
    - restart docker
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database

- name: Add docker0 interface to trusted zone
  become: yes
  firewalld:
    zone: trusted
    interface: docker0
    permanent: yes
    state: enabled
  notify:
    - reload-firewall
    - restart docker
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database

- name: Enable firewalld ports
  become: yes
  firewalld:
    port: "{{ item }}"
    zone: "{{ firewall_zone }}"
    permanent: yes
    state: enabled
  with_items: "{{ ports }}"
  notify:
    - reload-firewall
    - restart docker
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
