---
- name: Install Docker and dependencies
  become: yes
  yum:
    name: "{{ docker_packages }}" 
    state: latest
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database
    - docker

- name: Start and enable docker
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database
    - docker
