---
- name: Ensure that quay config is stopped
  become: yes
  podman_container:
    name: quay-config
    state: stopped
  ignore_errors: true
  tags:
    - quay

- name: Create quay config directory
  become: yes
  file:
    state: directory
    path: "{{ quay_root_dir }}/config"
  tags:
    - quay

- name: "Create quay storage directory (when object storage is not available)"
  become: yes
  file:
    state: directory
    path: "{{ quay_root_dir }}/storage"
  when: not quay_object_storage and quay_object_storage is defined
  tags:
    - quay

- name: Copy the tarball to the quay host
  become: yes
  unarchive:
    src: "{{ quay_config_tar }}"
    dest: "{{ quay_root_dir }}/config/"
    copy: yes
  tags:
    - quay
    - deploy-config

- name: Start quay
  become: yes
  podman_container:
    detach: yes
    restart: yes
    name: "{{ quay_container_name }}"
    privileged: yes
    env:
      DEBUGLOG: "true"
    published_ports:
      - "{{ quay_http_port }}:8080"
      - "{{ quay_https_port }}:8443"
    image: "{{ quay_image_version }}"
    volumes:
      - "{{ quay_root_dir }}/config:/conf/stack:Z"
      - "{{ quay_root_dir }}/storage:/datastorage:Z"
  tags:
    - quay
